language: ruby

rvm:
  - 2.7.5

cache:
  bundler: true
  yarn: true
  directories:
    - node_modules

install:
  - bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
  - nvm install $(grep 'node' .tool-versions | cut -d ' ' -f2)
  - npm i -g yarn
  - yarn

notifications:
  email: false
  slack:
    secure: YE9LirevstqJ9qglWo2C1IrFEObyThgS72ks0oikEyqKyx1UeEljX3OPX03k+fref/3Z2smtAMH2OgCaXi3cpLIDJI3J14EXOyzMHYz1ul1h52Qp5UrwbKIikD4Yi+RywVLGhLZMedKKI1D0MwcHlwSEuATyIJpZ7do28lEcuL0=
